object Versions {
    const val gradlePlugin = "7.1.2"
    const val kotlin = "1.6.10"
    const val timber = "5.0.1"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.2"
    const val googleService = "4.3.10"
    const val safeArgs = "2.4.1"
    const val hiltVersion = "2.40.1"
    const val hiltCompilerVersion = "1.0.0"
    const val hiltLifecycleVersion = "1.0.0-alpha03"
    const val firebase = "29.0.3"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val coroutines = "1.5.2"
    const val lifecycle = "2.4.0"
    const val lifecycleExt = "2.2.0"
    const val gson = "2.8.9"
    const val navigation = "2.4.0"
    const val glide = "4.12.0"
    const val preferences = "1.0.0"
    const val chuckEr = "3.5.2"
    const val firebaseAuthUi = "7.2.0"
    const val lottieVersion = "3.4.0"
    const val maps = "18.0.2"
    const val location = "19.0.1"
    const val shimmer = "0.5.0"

    // Testing
    const val jUnitVersion = "4.13.2"
    const val jUnitExtVersion = "1.1.3"
    const val espresso = "3.4.0"
    const val googleTruth = "1.1.3"
    const val mockito = "4.3.1"
}